version: "{build}"
skip_non_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:  
    secure: 4guKYW7T2AsE96Wgu0J9RFtVYKSYRxU3L/pzz8UxJpv6uXXSfizwTF4s7iKUDk32
  RocketServer:
    secure: m63NKaOYAewP8LyDKqbj/poe3GsUJcJL0IIbi58l3Is=
init:
- ps: $env:APPVEYOR_REPO_TAG_NAME
- ps: Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
before_build:
- ps: nuget restore Rocket.Chat.Net.sln
build:
  project: Rocket.Chat.Net.sln
  parallel: true
  verbosity: minimal
test_script:
- ps: .\test.ps1
deploy: off
artifacts:
- path: 'src\**\*.nupkg'